

version: '3.8'

services:
  app:
    build: ./spsearch
    ports:
      - "8001:8000"  # Expose FastAPI on port 8000
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - db  # Wait for the database to be ready
    volumes:
      - ./spsearch:/spsearch  # Mount the app directory

  db:
    build: ./postgres  # Use the custom Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/datanew  # Persist database data

volumes:
  pgdata:
